# Spring properties
spring:
  profiles: default
  application:
     name: solrchangemonitor  # Service registers under this name
  cloud:
      stream:
        bindings:
          contentChannel:
            binder: rabbit
            destination: work.exchange
            contentType: application/json
            #group: contentconsumer, lookup
  #rabbitmq:
      #password: "rabbitmq"
      #username: "rabbitmq"
  #jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/changemonitor
    username: root
    password: root

hibernate.dialect: org.hibernate.dialect.MySQLDialect

app.solrUrl: http://149.221.203.57:8983/solr/default_core/


logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management.health.db.enabled: true
management.health.defaults.enabled: true
management.health.diskspace.enabled: true
management.endpoint.health.show-details: always

---
spring:
  profiles: docker
  datasource:
      url: jdbc:mysql://db:3306/changemonitor

  rabbitmq:
    host: rabbitmq



